# Generated by Django 4.2.11 on 2026-04-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('RESET_PASSWORD', 'Reset Password'), ('TOGGLE_ACTIVE', 'Toggle Active'), ('EDIT_USER', 'Edit User'), ('CREATE_USER', 'Create User'), ('LOGIN', 'Login'), ('FAILED_LOGIN', 'Failed Login')], max_length=50),
        ),
    ]
