# Generated by Django 4.2.11 on 2026-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_failed_login_attempts_user_locked_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('RESET_PASSWORD', 'Reset Password'), ('TOGGLE_ACTIVE', 'Toggle Active'), ('EDIT_USER', 'Edit User'), ('CREATE_USER', 'Create User'), ('LOGIN', 'Login'), ('FAILED_LOGIN', 'Failed Login'), ('UNLOCK_USER', 'Unlock User')], max_length=50),
        ),
    ]
