# Generated by Django 4.2.11 on 2026-03-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_add_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
