# Generated by Django 4.2.11 on 2026-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_add_flexible_auto_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='payee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='payee_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='payee_recipient',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
