# Generated by Django 4.2.11 on 2026-04-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_merge_0004_and_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('sales', 'Sales'), ('maintenance', 'Maintenance')], default='sales', max_length=20),
        ),
    ]
