# Generated by Django 4.2.11 on 2026-04-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_billpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='billline',
            name='account_type',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('expense', 'Expense')], default='inventory', help_text='If Expense, treat this line as an operational expense rather than inventory/COGS', max_length=16),
        ),
    ]
