# Generated by Django 4.2.11 on 2026-02-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('services', '0001_initial'), ('services', '0002_service_parts'), ('services', '0003_add_car_fk')]

    initial = True

    # Keep this squashed migration self-contained for new installs.
    # Cross-app fields (M2M `parts` and FK `car`) are moved to a follow-up
    # migration to avoid circular dependency with `inventory` and `cars`.
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('paid', 'مدفوعة')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.department')),
            ],
        ),
    ]
