# Generated by Django 5.2.10 on 2026-02-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("customer_id", models.CharField(max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "نشط"), ("inactive", "معطل")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "communication_preference",
                    models.CharField(
                        choices=[
                            ("email", "البريد الإلكتروني"),
                            ("phone", "الهاتف"),
                            ("sms", "رسائل قصيرة"),
                        ],
                        default="phone",
                        max_length=10,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
