# Generated by Django 4.2.11 on 2026-03-08 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'معطل')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('communication_preference', models.CharField(choices=[('email', 'البريد الإلكتروني'), ('phone', 'الهاتف'), ('sms', 'رسائل قصيرة')], default='phone', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
