# Generated by Django 4.2.11 on 2026-02-12 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('inventory', '0001_initial'), ('inventory', '0002_purchaseitem'), ('inventory', '0003_remove_part_supplier_part_suppliers'), ('inventory', '0004_part_purchase_price_part_sale_price'), ('inventory', '0005_part_is_stock_item'), ('inventory', '0006_recreate_purchase'), ('inventory', '0007_part_track_purchases_part_track_sales')]

    initial = True

    # Temporarily remove cross-app dependency to allow recording squashed migrations
    # in environments where the services follow-up migration isn't applied yet.
    # This file is a squashed initial migration; in a fresh install the
    # follow-up migrations will be applied in order. Adjusting dependencies
    # here only affects local recording for the cleanup process.
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_return', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_alert', models.PositiveIntegerField(default=5)),
                ('suppliers', models.ManyToManyField(blank=True, related_name='parts', to='inventory.supplier')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_stock_item', models.BooleanField(default=True)),
                ('track_purchases', models.BooleanField(default=True)),
                ('track_sales', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='inventory.part')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase')),
            ],
        ),
    ]
