# Generated by Django 4.2.11 on 2026-02-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='supplier',
        ),
        migrations.AddField(
            model_name='part',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='parts', to='inventory.supplier'),
        ),
    ]
