# Generated by Django 4.2.11 on 2026-02-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_part_code_part_purchase_price_part_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.supplier'),
        ),
    ]
