# Generated by Django 4.2.11 on 2026-02-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_part_supplier_part_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='part',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
