# Generated by Django 4.2.11 on 2026-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_part_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
