# Generated by Django 4.2.11 on 2026-02-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_part_purchase_price_part_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_stock_item',
            field=models.BooleanField(default=True),
        ),
    ]
