# Generated by Django 4.2.11 on 2026-02-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_part_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_purchase',
            field=models.BooleanField(default=True, help_text='If true, this part can be purchased from suppliers'),
        ),
        migrations.AddField(
            model_name='part',
            name='is_sale',
            field=models.BooleanField(default=True, help_text='If true, this part can be sold to customers'),
        ),
        migrations.AddField(
            model_name='part',
            name='track_stock',
            field=models.BooleanField(default=False, help_text='If true, selling this part will decrement stock quantity'),
        ),
    ]
