# Generated by Django 4.2.11 on 2026-02-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_recreate_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='track_purchases',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='part',
            name='track_sales',
            field=models.BooleanField(default=True),
        ),
    ]
