# Generated by Django 4.2.11 on 2026-02-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_part_is_purchase_part_is_sale_part_track_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['code', 'name']},
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
