# Generated by Django 4.2.11 on 2026-04-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_part_options_supplier_supplier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_inventory',
            field=models.BooleanField(default=True, help_text='If true, this part is inventory and contributes to COGS; if false it is treated as an expense'),
        ),
    ]
