# Django settings for workshop project.
#
# Generated by 'django-admin startproject' using Django 6.0.1.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
"""
Module configuration and settings for the Workshop project.
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# دعم CSRF مع ngrok
CSRF_TRUSTED_ORIGINS = ["https://lizabeth-slippy-camilla.ngrok-free.dev"]
# صفحة تسجيل الدخول الافتراضية
LOGIN_URL = "/users/login/"
# الصفحة التي يتم إعادة التوجيه إليها بعد تسجيل الدخول
LOGIN_REDIRECT_URL = "/dashboard/"
# الحقل الافتراضي لإنشاء الحقول التلقائية في النماذج
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# استخدم المسار الديناميكي الصحيح للمشروع
BASE_DIR = Path(__file__).resolve().parent.parent

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"

# مجلدات static أثناء التطوير
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# مكان تخزين الملفات عند رفع الموقع للإنتاج
STATIC_ROOT = BASE_DIR / "staticfiles"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY: load secret key and debug mode from environment
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable not set")

# SECURITY: default DEBUG to False unless explicitly enabled via env
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    "192.168.10.200",
    "localhost",
    "127.0.0.1",
    "lizabeth-slippy-camilla.ngrok-free.dev",
    "altaakhitowers.com",
    "www.altaakhitowers.com",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "clients",
    "cars",
    "services",
    "inventory",
    "invoices",
    "reports",
    "settings",
    "bookings",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "workshop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "workshop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Custom user model
AUTH_USER_MODEL = "users.User"
