# دعم CSRF مع ngrok
CSRF_TRUSTED_ORIGINS = [
    'https://lizabeth-slippy-camilla.ngrok-free.dev',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]
# صفحة تسجيل الدخول الافتراضية
LOGIN_URL = '/users/login/'
# الصفحة التي يتم إعادة التوجيه إليها بعد تسجيل الدخول
LOGIN_REDIRECT_URL = '/dashboard/'
# الصفحة التي يتم إعادة التوجيه إليها بعد تسجيل الخروج
LOGOUT_REDIRECT_URL = '/'
# الحقل الافتراضي لإنشاء الحقول التلقائية في النماذج
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
"""
Django settings for workshop project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# استخدم المسار الديناميكي الصحيح للمشروع
BASE_DIR = Path(__file__).resolve().parent.parent

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# مجلدات static أثناء التطوير
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# مكان تخزين الملفات عند رفع الموقع للإنتاج
STATIC_ROOT = BASE_DIR / "staticfiles"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2*bo+%d$4tzfhi&l@=_scanjgctm3(0auwr_wp^#_897i-=817'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '192.168.10.200',
    'localhost',
    '127.0.0.1',
    'testserver',
    'lizabeth-slippy-camilla.ngrok-free.dev',
    'altaakhitowers.com',
    'www.altaakhitowers.com'
]

# Note: 'testserver' is used by Django Test Client; keep it for local test runs.


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'clients',
    'cars',
    'services',
    'inventory',
    'invoices',
    'bills',
    'reports',
    'settings',
    'bookings',
]

MIDDLEWARE = [
    'workshop.middleware.RemoveInventorySearchMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'workshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'workshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Use file-based backend for local development: emails are written to files
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = BASE_DIR / 'sent_emails'
# Default sender address (display name + address)
DEFAULT_FROM_EMAIL = 'Altaakhi Workshop <dreamtop@gmail.com>'

# SMTP send example (uncomment and provide credentials to send real email):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
# EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
# EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')  # e.g. dreamtop@gmail.com
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  # app password or SMTP password
# Note: For Gmail, you must use an App Password (or configure OAuth) - see Google account security settings.
