# Generated by Django 6.0.1 on 2026-02-02 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "__first__"),
        ("invoices", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الخدمة الفنية"
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="سعر الخدمة",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="cars.carbrand",
                    ),
                ),
            ],
            options={
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=20, unique=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("gasoline", "بنزين"),
                            ("diesel", "ديزل"),
                            ("electric", "كهرباء"),
                            ("hybrid", "هايبرد"),
                        ],
                        default="gasoline",
                        max_length=10,
                    ),
                ),
                (
                    "vin_number",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشطة"),
                            ("ready", "بانتظار التسليم"),
                            ("pending_payment", "معلقة للدفع"),
                            ("sold", "مباعة"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "entry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ دخول الورشة"
                    ),
                ),
                ("last_visit", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="clients.client",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cars",
                        to="cars.carbrand",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cars",
                        to="cars.carmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ تسليم المركبة"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "ready_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ انتهاء التصليح"
                    ),
                ),
                (
                    "is_finished",
                    models.BooleanField(
                        default=False, verbose_name="تم الانتهاء من الصيانة"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="cars.car",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_records",
                        to="invoices.invoice",
                        verbose_name="رقم الفاتورة",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                    ),
                ),
            ],
        ),
    ]
