# Generated by Django 4.2.11 on 2026-02-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_add_invoice_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('waiting', 'قيد الانتظار'), ('in_progress', 'جاري التنفيذ'), ('pending_payment', 'معلقة للدفع'), ('paid_waiting_collection', 'مدفوعة - بانتظار الاستلام'), ('done', 'مُنتهية'), ('active', 'نشطة'), ('ready', 'بانتظار التسليم'), ('sold', 'مباعة')], default='waiting', max_length=32),
        ),
    ]
