# Generated by Django 4.2.11 on 2026-03-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
