# Generated by Django 5.2.10 on 2026-02-02 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cars", "0001_initial"),
        ("invoices", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerecord",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_records",
                to="invoices.invoice",
                verbose_name="رقم الفاتورة",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="services.service"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carmodel",
            unique_together={("brand", "name")},
        ),
    ]
