from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(null=True, blank=True, to='clients.client', on_delete=django.db.models.deletion.CASCADE, related_name='bookings'),
        ),
    ]
# Generated by Django 6.0.1 on 2026-02-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_client_field'),
    ]

    operations = [
    ]
