# Generated by Django 6.0.1 on 2026-02-02 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = []
